import { Car, CarTypes, FuelTypes, Transmissions } from "@/common.types";

const carImgPath = "/images/cars/";
const makeImgPath = "/images/makes/";

interface Make {
  name: string;
  image: string;
  cars: Car[];
}

export const makes: Make[] = [
  // Audi
  {
    name: "Audi",
    image: makeImgPath + "audi.svg",
    cars: [
      {
        model: "A3",
        type: CarTypes.SEDAN,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmissions.MANUAL,
        fuelType: FuelTypes.DIESEL,
        fuelConsumption: "5.0 L/100 km",
        isActive: true,
        showInMain: false,
        image: carImgPath + "audi-a3-2023.png",
      },
      {
        model: "A6",
        type: CarTypes.SEDAN,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmissions.AUTOMATIC,
        fuelType: FuelTypes.DIESEL,
        fuelConsumption: "8 L/100 km",
        isActive: true,
        showInMain: false,
        image: carImgPath + "audi-a6-2023.png",
      },
      {
        model: "Q3",
        type: CarTypes.SUV,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmissions.AUTOMATIC,
        fuelType: FuelTypes.GASOLINE,
        fuelConsumption: "5.5 L/100 km",
        isActive: true,
        showInMain: false,
        image: carImgPath + "audi-q3-2023.png",
      },
      {
        model: "Q8",
        type: CarTypes.SUV,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmissions.AUTOMATIC,
        fuelType: FuelTypes.GASOLINE,
        fuelConsumption: "8.5 L/100 km",
        isActive: true,
        showInMain: false,
        image: carImgPath + "audi-q8-2023.png",
      },
    ],
  },
  // Volkswagen
  {
    name: "Volkswagen",
    image: makeImgPath + "volkswagen.svg",
    cars: [
      {
        model: "Golf GTI",
        type: CarTypes.HATCHBACK,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmissions.AUTOMATIC,
        fuelType: FuelTypes.GASOLINE,
        fuelConsumption: " L/100 km",
        isActive: true,
        showInMain: false,
        image: carImgPath + "volkswagen-golf-gti-2023.png",
      },
      {
        model: "Golf R",
        type: CarTypes.HATCHBACK,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmissions.AUTOMATIC,
        fuelType: FuelTypes.GASOLINE,
        fuelConsumption: " L/100 km",
        isActive: true,
        showInMain: false,
        image: carImgPath + "volkswagen-golf-r-2023.png",
      },
      {
        model: "Tiguan",
        type: CarTypes.SUV,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmissions.AUTOMATIC,
        fuelType: FuelTypes.GASOLINE,
        fuelConsumption: " L/100 km",
        isActive: true,
        showInMain: false,
        image: carImgPath + "volkswagen-tiguan-2023.png",
      },
      {
        model: "Touareg",
        type: CarTypes.SUV,
        year: 2017,
        doors: 5,
        seats: 5,
        transmission: Transmissions.AUTOMATIC,
        fuelType: FuelTypes.GASOLINE,
        fuelConsumption: " L/100 km",
        isActive: true,
        showInMain: true,
        image: carImgPath + "volkswagen-touareg-2017.png",
      },
      {
        model: "Tiguan",
        type: CarTypes.SUV,
        year: 2023,
        doors: 5,
        seats: 7,
        transmission: Transmissions.AUTOMATIC,
        fuelType: FuelTypes.GASOLINE,
        fuelConsumption: " L/100 km",
        isActive: true,
        showInMain: false,
        image: carImgPath + "volkswagen-tiguan-2023.png",
      },
      {
        model: "T-Roc",
        type: CarTypes.SUV,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmissions.AUTOMATIC,
        fuelType: FuelTypes.GASOLINE,
        fuelConsumption: " L/100 km",
        isActive: true,
        showInMain: true,
        image: carImgPath + "volkswagen-t-roc-2023.png",
      },
    ],
  },
  // Porsche
  {
    name: "Porsche",
    image: makeImgPath + "porsche.svg",
    cars: [
      {
        model: "Macan",
        type: CarTypes.SUV,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmissions.AUTOMATIC,
        fuelType: FuelTypes.GASOLINE,
        fuelConsumption: " L/100 km",
        isActive: true,
        showInMain: false,
        image: carImgPath + "porsche-macan-2023.png",
      },
    ],
  },
  // Mercedes-Benz
  {
    name: "Mercedes-Benz",
    image: makeImgPath + "mercedes-benz.svg",
    cars: [
      {
        model: "A-Class",
        type: CarTypes.SEDAN,
        year: 2022,
        doors: 5,
        seats: 5,
        transmission: Transmissions.AUTOMATIC,
        fuelType: FuelTypes.GASOLINE,
        fuelConsumption: " L/100 km",
        isActive: true,
        showInMain: false,
        image: carImgPath + "mercedes-benz-a-class-2022.png",
      },
      {
        model: "C-Class",
        type: CarTypes.SEDAN,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmissions.AUTOMATIC,
        fuelType: FuelTypes.GASOLINE,
        fuelConsumption: " L/100 km",
        isActive: true,
        showInMain: false,
        image: carImgPath + "mercedes-benz-c-class-2023.png",
      },
      {
        model: "E-Class",
        type: CarTypes.SEDAN,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmissions.AUTOMATIC,
        fuelType: FuelTypes.GASOLINE,
        fuelConsumption: " L/100 km",
        isActive: true,
        showInMain: false,
        image: carImgPath + "mercedes-benz-e-class-2023.png",
      },
      {
        model: "Metris",
        type: CarTypes.SEDAN,
        year: 2022,
        doors: 5,
        seats: 8,
        transmission: Transmissions.MANUAL,
        fuelType: FuelTypes.DIESEL,
        fuelConsumption: " L/100 km",
        isActive: true,
        showInMain: false,
        image: carImgPath + "mercedes-benz-metris-passenger-2022.png",
      },
      {
        model: "Mercedes-AMG G-Class",
        type: CarTypes.SUV,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmissions.AUTOMATIC,
        fuelType: FuelTypes.DIESEL,
        fuelConsumption: "14.07 L/100 km",
        isActive: true,
        showInMain: false,
        image: carImgPath + "mercedes-benz-mercedes-amg-g-class-2023.png",
      },
    ],
  },
  // Renault
  {
    name: "Renault",
    image: makeImgPath + "renault.svg",
    cars: [
      {
        model: "Clio",
        type: CarTypes.HATCHBACK,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmissions.MANUAL,
        fuelType: FuelTypes.DIESEL,
        fuelConsumption: "5.2 L/100 km",
        isActive: true,
        showInMain: true,
        image: carImgPath + "renault-clio-2023.png",
      },
      {
        model: "Express",
        type: CarTypes.VAN,
        year: 2023,
        doors: 6,
        seats: 5,
        transmission: Transmissions.MANUAL,
        fuelType: FuelTypes.DIESEL,
        fuelConsumption: "5.2 L/100 km",
        isActive: true,
        showInMain: false,
        image: carImgPath + "renault-express-2023.png",
      },
      {
        model: "Megane",
        type: CarTypes.HATCHBACK,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmissions.MANUAL,
        fuelType: FuelTypes.DIESEL,
        fuelConsumption: " L/100 km",
        isActive: true,
        showInMain: false,
        image: carImgPath + "renault-megane-2023.png",
      },
      {
        model: "Megane Sedan",
        type: CarTypes.SEDAN,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmissions.MANUAL,
        fuelType: FuelTypes.DIESEL,
        fuelConsumption: " L/100 km",
        isActive: true,
        showInMain: false,
        image: carImgPath + "renault-megane-sedan-2023.png",
      },
    ],
  },
  // Dacia
  {
    name: "Dacia",
    image: makeImgPath + "dacia.svg",
    cars: [
      {
        model: "Logan",
        type: CarTypes.SEDAN,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmissions.MANUAL,
        fuelType: FuelTypes.DIESEL,
        fuelConsumption: "4.5 L/100 km",
        isActive: true,
        showInMain: true,
        image: carImgPath + "dacia-logan.png",
      },
      {
        model: "Duster",
        type: CarTypes.SUV,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmissions.MANUAL,
        fuelType: FuelTypes.DIESEL,
        fuelConsumption: " L/100 km",
        isActive: true,
        showInMain: false,
        image: carImgPath + "dacia-duster-2023.png",
      },
      {
        model: "Duster Extreme",
        type: CarTypes.SUV,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmissions.MANUAL,
        fuelType: FuelTypes.DIESEL,
        fuelConsumption: " L/100 km",
        isActive: true,
        showInMain: true,
        image: carImgPath + "dacia-duster-extreme-2023.png",
      },
    ],
  },
  // Fiat
  {
    name: "Fiat",
    image: makeImgPath + "fiat.svg",
    cars: [
      {
        model: "Tipo",
        type: CarTypes.SEDAN,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmissions.MANUAL,
        fuelType: FuelTypes.DIESEL,
        fuelConsumption: " L/100 km",
        isActive: true,
        showInMain: true,
        image: carImgPath + "fiat-tipo.png",
      },
      {
        model: "Doblo",
        type: CarTypes.VAN,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmissions.MANUAL,
        fuelType: FuelTypes.DIESEL,
        fuelConsumption: " L/100 km",
        isActive: true,
        showInMain: false,
        image: carImgPath + "fiat-doblo.png",
      },
      {
        model: "Fiorino",
        type: CarTypes.VAN,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmissions.MANUAL,
        fuelType: FuelTypes.DIESEL,
        fuelConsumption: " L/100 km",
        isActive: true,
        showInMain: false,
        image: carImgPath + "fiat-fiorino.png",
      },
      {
        model: "500",
        type: CarTypes.HATCHBACK,
        year: 2019,
        doors: 3,
        seats: 4,
        transmission: Transmissions.MANUAL,
        fuelType: FuelTypes.GASOLINE,
        fuelConsumption: " L/100 km",
        isActive: true,
        showInMain: false,
        image: carImgPath + "fiat-500-2019.png",
      },
    ],
  },
  // Hyundai
  {
    name: "Hyundai",
    image: makeImgPath + "hyundai.svg",
    cars: [
      {
        model: "Accent",
        type: CarTypes.SEDAN,
        year: 2022,
        doors: 4,
        seats: 5,
        transmission: Transmissions.MANUAL,
        fuelType: FuelTypes.DIESEL,
        fuelConsumption: "4.5 L/100 km",
        isActive: true,
        showInMain: true,
        image: carImgPath + "hyundai-accent-2022.png",
      },
      {
        model: "Tucson",
        type: CarTypes.SUV,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmissions.AUTOMATIC,
        fuelType: FuelTypes.GASOLINE,
        fuelConsumption: "6 L/100 km",
        isActive: true,
        showInMain: true,
        image: carImgPath + "hyundai-tucson-2023.png",
      },
      {
        model: "i10",
        type: CarTypes.HATCHBACK,
        year: 2021,
        doors: 5,
        seats: 5,
        transmission: Transmissions.MANUAL,
        fuelType: FuelTypes.GASOLINE,
        fuelConsumption: "6 L/100 km",
        isActive: true,
        showInMain: false,
        image: carImgPath + "hyundai-i10-2021.png",
      },
      {
        model: "i30",
        type: CarTypes.HATCHBACK,
        year: 2021,
        doors: 5,
        seats: 5,
        transmission: Transmissions.MANUAL,
        fuelType: FuelTypes.DIESEL,
        fuelConsumption: " L/100 km",
        isActive: true,
        showInMain: false,
        image: carImgPath + "hyundai-i30-2021.png",
      },
      {
        model: "Elantra",
        type: CarTypes.SEDAN,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmissions.AUTOMATIC,
        fuelType: FuelTypes.DIESEL,
        fuelConsumption: " L/100 km",
        isActive: true,
        showInMain: false,
        image: carImgPath + "hyundai-elantra-2023.png",
      },
      {
        model: "Creta",
        type: CarTypes.SUV,
        year: 2021,
        doors: 5,
        seats: 5,
        transmission: Transmissions.MANUAL,
        fuelType: FuelTypes.DIESEL,
        fuelConsumption: " L/100 km",
        isActive: true,
        showInMain: true,
        image: carImgPath + "hyundai-creta-2021.png",
      },
      {
        model: "Santa fe",
        type: CarTypes.SUV,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmissions.AUTOMATIC,
        fuelType: FuelTypes.DIESEL,
        fuelConsumption: "7.2 L/100 km",
        isActive: true,
        showInMain: false,
        image: carImgPath + "hyundai-santa-fe-2023.png",
      },
    ],
  },
  // Jeep
  {
    name: "Jeep",
    image: makeImgPath + "jeep.svg",
    cars: [
      {
        model: "Renegade",
        type: CarTypes.SUV,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmissions.AUTOMATIC,
        fuelType: FuelTypes.GASOLINE,
        fuelConsumption: " L/100 km",
        isActive: true,
        showInMain: false,
        image: carImgPath + "jeep-renegade-2023.png",
      },
      {
        model: "Cherokee",
        type: CarTypes.SUV,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmissions.MANUAL,
        fuelType: FuelTypes.GASOLINE,
        fuelConsumption: " L/100 km",
        isActive: true,
        showInMain: false,
        image: carImgPath + "jeep-cherokee-2023.png",
      },
    ],
  },
  // Citroen
  {
    name: "Citroen",
    image: makeImgPath + "citroen.svg",
    cars: [
      {
        model: "C3",
        type: CarTypes.HATCHBACK,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmissions.MANUAL,
        fuelType: FuelTypes.DIESEL,
        fuelConsumption: " L/100 km",
        isActive: true,
        showInMain: false,
        image: carImgPath + "citroen-c3-2023.png",
      },
      {
        model: "C4",
        type: CarTypes.SUV,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmissions.MANUAL,
        fuelType: FuelTypes.DIESEL,
        fuelConsumption: "7.3 L/100 km",
        isActive: true,
        showInMain: false,
        image: carImgPath + "citroen-c4-2023.png",
      },
    ],
  },
  // Land Rover
  {
    name: "Land Rover",
    image: makeImgPath + "land-rover.svg",
    cars: [
      {
        model: "Range Rover Evoque",
        type: CarTypes.SUV,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmissions.AUTOMATIC,
        fuelType: FuelTypes.DIESEL,
        fuelConsumption: " L/100 km",
        isActive: true,
        showInMain: false,
        image: carImgPath + "land-rover-range-rover-evoque-2023.png",
      },
      {
        model: "Range Rover Sport",
        type: CarTypes.SUV,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmissions.AUTOMATIC,
        fuelType: FuelTypes.GASOLINE,
        fuelConsumption: "9.5 L/100 km",
        isActive: true,
        showInMain: false,
        image: carImgPath + "land-rover-range-rover-sport-2023.png",
      },
    ],
  },
];
