import { Car, CarType, FuelType, Transmission } from "@/common.types";

const carImgPath = "/images/cars/";
const makeImgPath = "/images/makes/";

interface Make {
  name: string;
  image: string;
  cars: Car[];
}

export const makes: Make[] = [
  // Audi
  {
    name: "Audi",
    image: makeImgPath + "audi.svg",
    cars: [
      {
        model: "A3",
        type: CarType.HATCHBACK,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmission.MANUAL,
        fuelType: FuelType.DIESEL,
        fuelConsumption: "5.0 L/100 km",
        price: "",
        isActive: true,
        showInMain: false,
        image: carImgPath + "audi-a3-2023.webp",
      },
      {
        model: "A6",
        type: CarType.SEDAN,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmission.AUTOMATIC,
        fuelType: FuelType.DIESEL,
        fuelConsumption: "8 L/100 km",
        price: "",
        isActive: true,
        showInMain: false,
        image: carImgPath + "audi-a6-2023.webp",
      },
      {
        model: "Q3",
        type: CarType.SUV,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmission.AUTOMATIC,
        fuelType: FuelType.GASOLINE,
        fuelConsumption: "5.5 L/100 km",
        price: "",
        isActive: true,
        showInMain: false,
        image: carImgPath + "audi-q3-2023.webp",
      },
      {
        model: "Q8",
        type: CarType.SUV,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmission.AUTOMATIC,
        fuelType: FuelType.GASOLINE,
        fuelConsumption: "8.5 L/100 km",
        price: "",
        isActive: true,
        showInMain: true,
        image: carImgPath + "audi-q8-2023.webp",
      },
    ],
  },
  // Volkswagen
  {
    name: "Volkswagen",
    image: makeImgPath + "volkswagen.svg",
    cars: [
      {
        model: "Golf",
        type: CarType.HATCHBACK,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmission.AUTOMATIC,
        fuelType: FuelType.GASOLINE,
        fuelConsumption: " L/100 km",
        price: "",
        isActive: true,
        showInMain: true,
        image: carImgPath + "volkswagen-golf.webp",
      },
      {
        model: "Tiguan",
        type: CarType.SUV,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmission.AUTOMATIC,
        fuelType: FuelType.GASOLINE,
        fuelConsumption: " L/100 km",
        price: "",
        isActive: true,
        showInMain: false,
        image: carImgPath + "volkswagen-tiguan.webp",
      },
      {
        model: "Touareg",
        type: CarType.SUV,
        year: 2017,
        doors: 5,
        seats: 5,
        transmission: Transmission.AUTOMATIC,
        fuelType: FuelType.GASOLINE,
        fuelConsumption: " L/100 km",
        price: "",
        isActive: true,
        showInMain: true,
        image: carImgPath + "volkswagen-touareg.webp",
      },
      {
        model: "Tiguan",
        type: CarType.SUV,
        year: 2023,
        doors: 5,
        seats: 7,
        transmission: Transmission.AUTOMATIC,
        fuelType: FuelType.GASOLINE,
        fuelConsumption: " L/100 km",
        price: "",
        isActive: true,
        showInMain: false,
        image: carImgPath + "volkswagen-tiguan.webp",
      },
      {
        model: "T-Roc",
        type: CarType.SUV,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmission.AUTOMATIC,
        fuelType: FuelType.GASOLINE,
        fuelConsumption: " L/100 km",
        price: "",
        isActive: true,
        showInMain: true,
        image: carImgPath + "volkswagen-t-roc.webp",
      },
    ],
  },
  // Porsche
  {
    name: "Porsche",
    image: makeImgPath + "porsche.svg",
    cars: [
      {
        model: "Macan",
        type: CarType.SUV,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmission.AUTOMATIC,
        fuelType: FuelType.GASOLINE,
        fuelConsumption: " L/100 km",
        price: "",
        isActive: true,
        showInMain: true,
        image: carImgPath + "porsche-macan-2023.webp",
      },
    ],
  },
  // Mercedes-Benz
  {
    name: "Mercedes-Benz",
    image: makeImgPath + "mercedes-benz.svg",
    cars: [
      {
        model: "A-Class",
        type: CarType.SEDAN,
        year: 2022,
        doors: 5,
        seats: 5,
        transmission: Transmission.AUTOMATIC,
        fuelType: FuelType.GASOLINE,
        fuelConsumption: " L/100 km",
        price: "",
        isActive: true,
        showInMain: false,
        image: carImgPath + "mercedes-benz-a-class.webp",
      },
      {
        model: "C-Class",
        type: CarType.SEDAN,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmission.AUTOMATIC,
        fuelType: FuelType.GASOLINE,
        fuelConsumption: " L/100 km",
        price: "",
        isActive: true,
        showInMain: false,
        image: carImgPath + "mercedes-benz-c-class.webp",
      },
      {
        model: "E-Class",
        type: CarType.SEDAN,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmission.AUTOMATIC,
        fuelType: FuelType.GASOLINE,
        fuelConsumption: " L/100 km",
        price: "",
        isActive: true,
        showInMain: false,
        image: carImgPath + "mercedes-benz-e-class.webp",
      },
      {
        model: "Vito",
        type: CarType.SEDAN,
        year: 2022,
        doors: 5,
        seats: 8,
        transmission: Transmission.MANUAL,
        fuelType: FuelType.DIESEL,
        fuelConsumption: " L/100 km",
        price: "",
        isActive: true,
        showInMain: false,
        image: carImgPath + "mercedes-benz-vito.webp",
      },
      {
        model: "Mercedes-AMG G-Class",
        type: CarType.SUV,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmission.AUTOMATIC,
        fuelType: FuelType.DIESEL,
        fuelConsumption: "14.07 L/100 km",
        price: "",
        isActive: true,
        showInMain: false,
        image: carImgPath + "mercedes-benz-mercedes-amg-g-class-2023.webp",
      },
    ],
  },
  // Renault
  {
    name: "Renault",
    image: makeImgPath + "renault.svg",
    cars: [
      {
        model: "Clio",
        type: CarType.HATCHBACK,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmission.MANUAL,
        fuelType: FuelType.DIESEL,
        fuelConsumption: "5.2 L/100 km",
        price: "",
        isActive: true,
        showInMain: true,
        image: carImgPath + "renault-clio-2023.webp",
      },
      {
        model: "Express",
        type: CarType.VAN,
        year: 2023,
        doors: 6,
        seats: 5,
        transmission: Transmission.MANUAL,
        fuelType: FuelType.DIESEL,
        fuelConsumption: "5.2 L/100 km",
        price: "",
        isActive: true,
        showInMain: false,
        image: carImgPath + "renault-express-2023.webp",
      },
      {
        model: "Megane",
        type: CarType.HATCHBACK,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmission.MANUAL,
        fuelType: FuelType.DIESEL,
        fuelConsumption: " L/100 km",
        price: "",
        isActive: true,
        showInMain: false,
        image: carImgPath + "renault-megane-2023.webp",
      },
      {
        model: "Megane Sedan",
        type: CarType.SEDAN,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmission.MANUAL,
        fuelType: FuelType.DIESEL,
        fuelConsumption: " L/100 km",
        price: "",
        isActive: true,
        showInMain: false,
        image: carImgPath + "renault-megane-sedan-2023.webp",
      },
    ],
  },
  // Dacia
  {
    name: "Dacia",
    image: makeImgPath + "dacia.svg",
    cars: [
      {
        model: "Logan",
        type: CarType.SEDAN,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmission.MANUAL,
        fuelType: FuelType.DIESEL,
        fuelConsumption: "4.5 L/100 km",
        price: "",
        isActive: true,
        showInMain: false,
        image: carImgPath + "dacia-logan.webp",
      },
      {
        model: "Duster",
        type: CarType.SUV,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmission.MANUAL,
        fuelType: FuelType.DIESEL,
        fuelConsumption: " L/100 km",
        price: "",
        isActive: true,
        showInMain: false,
        image: carImgPath + "dacia-duster-2023.webp",
      },
      {
        model: "Duster Extreme",
        type: CarType.SUV,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmission.AUTOMATIC,
        fuelType: FuelType.DIESEL,
        fuelConsumption: " L/100 km",
        price: "",
        isActive: true,
        showInMain: true,
        image: carImgPath + "dacia-duster-extreme-2023.webp",
      },
    ],
  },
  // Fiat
  {
    name: "Fiat",
    image: makeImgPath + "fiat.svg",
    cars: [
      {
        model: "Tipo",
        type: CarType.SEDAN,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmission.MANUAL,
        fuelType: FuelType.DIESEL,
        fuelConsumption: " L/100 km",
        price: "",
        isActive: true,
        showInMain: true,
        image: carImgPath + "fiat-tipo.webp",
      },
      {
        model: "Doblo",
        type: CarType.VAN,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmission.MANUAL,
        fuelType: FuelType.DIESEL,
        fuelConsumption: " L/100 km",
        price: "",
        isActive: true,
        showInMain: false,
        image: carImgPath + "fiat-doblo.webp",
      },
      {
        model: "Fiorino",
        type: CarType.VAN,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmission.MANUAL,
        fuelType: FuelType.DIESEL,
        fuelConsumption: " L/100 km",
        price: "",
        isActive: true,
        showInMain: false,
        image: carImgPath + "fiat-fiorino.webp",
      },
      {
        model: "500",
        type: CarType.HATCHBACK,
        year: 2019,
        doors: 3,
        seats: 4,
        transmission: Transmission.MANUAL,
        fuelType: FuelType.GASOLINE,
        fuelConsumption: " L/100 km",
        price: "",
        isActive: true,
        showInMain: true,
        image: carImgPath + "fiat-500.webp",
      },
    ],
  },
  // Hyundai
  {
    name: "Hyundai",
    image: makeImgPath + "hyundai.svg",
    cars: [
      {
        model: "Accent",
        type: CarType.SEDAN,
        year: 2022,
        doors: 4,
        seats: 5,
        transmission: Transmission.MANUAL,
        fuelType: FuelType.DIESEL,
        fuelConsumption: "4.5 L/100 km",
        price: "",
        isActive: true,
        showInMain: true,
        image: carImgPath + "hyundai-accent-2022.webp",
      },
      {
        model: "Tucson",
        type: CarType.SUV,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmission.AUTOMATIC,
        fuelType: FuelType.GASOLINE,
        fuelConsumption: "6 L/100 km",
        price: "",
        isActive: true,
        showInMain: true,
        image: carImgPath + "hyundai-tucson-2023.webp",
      },
      {
        model: "i10",
        type: CarType.HATCHBACK,
        year: 2021,
        doors: 5,
        seats: 5,
        transmission: Transmission.MANUAL,
        fuelType: FuelType.GASOLINE,
        fuelConsumption: "6 L/100 km",
        price: "",
        isActive: true,
        showInMain: false,
        image: carImgPath + "hyundai-i10-2021.webp",
      },
      {
        model: "i30",
        type: CarType.HATCHBACK,
        year: 2021,
        doors: 5,
        seats: 5,
        transmission: Transmission.MANUAL,
        fuelType: FuelType.DIESEL,
        fuelConsumption: " L/100 km",
        price: "",
        isActive: true,
        showInMain: false,
        image: carImgPath + "hyundai-i30-2023.webp",
      },
      {
        model: "Elantra",
        type: CarType.SEDAN,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmission.AUTOMATIC,
        fuelType: FuelType.DIESEL,
        fuelConsumption: " L/100 km",
        price: "",
        isActive: true,
        showInMain: false,
        image: carImgPath + "hyundai-elantra-2023.webp",
      },
      {
        model: "Creta",
        type: CarType.SUV,
        year: 2021,
        doors: 5,
        seats: 5,
        transmission: Transmission.MANUAL,
        fuelType: FuelType.DIESEL,
        fuelConsumption: " L/100 km",
        price: "",
        isActive: true,
        showInMain: true,
        image: carImgPath + "hyundai-creta-2022.webp",
      },
      {
        model: "Santa fe",
        type: CarType.SUV,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmission.AUTOMATIC,
        fuelType: FuelType.DIESEL,
        fuelConsumption: "7.2 L/100 km",
        price: "",
        isActive: true,
        showInMain: false,
        image: carImgPath + "hyundai-santa-fe-2023.webp",
      },
    ],
  },
  // Jeep
  {
    name: "Jeep",
    image: makeImgPath + "jeep.svg",
    cars: [
      {
        model: "Renegade",
        type: CarType.SUV,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmission.AUTOMATIC,
        fuelType: FuelType.GASOLINE,
        fuelConsumption: " L/100 km",
        price: "",
        isActive: true,
        showInMain: false,
        image: carImgPath + "jeep-renegade-2023.webp",
      },
      {
        model: "Cherokee",
        type: CarType.SUV,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmission.MANUAL,
        fuelType: FuelType.GASOLINE,
        fuelConsumption: " L/100 km",
        price: "",
        isActive: true,
        showInMain: false,
        image: carImgPath + "jeep-cherokee-2023.webp",
      },
    ],
  },
  // Citroen
  {
    name: "Citroen",
    image: makeImgPath + "citroen.svg",
    cars: [
      {
        model: "C3",
        type: CarType.HATCHBACK,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmission.MANUAL,
        fuelType: FuelType.DIESEL,
        fuelConsumption: " L/100 km",
        price: "",
        isActive: true,
        showInMain: false,
        image: carImgPath + "citroen-c3-2023.webp",
      },
      {
        model: "C4",
        type: CarType.SUV,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmission.MANUAL,
        fuelType: FuelType.DIESEL,
        fuelConsumption: "7.3 L/100 km",
        price: "",
        isActive: true,
        showInMain: false,
        image: carImgPath + "citroen-c4-2023.webp",
      },
    ],
  },
  // Land Rover
  {
    name: "Land Rover",
    image: makeImgPath + "land-rover.svg",
    cars: [
      {
        model: "Range Rover Evoque",
        type: CarType.SUV,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmission.AUTOMATIC,
        fuelType: FuelType.DIESEL,
        fuelConsumption: " L/100 km",
        price: "",
        isActive: true,
        showInMain: true,
        image: carImgPath + "land-rover-range-rover-evoque-2023.webp",
      },
      {
        model: "Range Rover Sport",
        type: CarType.SUV,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmission.AUTOMATIC,
        fuelType: FuelType.GASOLINE,
        fuelConsumption: "9.5 L/100 km",
        price: "",
        isActive: true,
        showInMain: true,
        image: carImgPath + "land-rover-range-rover-sport-2023.webp",
      },
    ],
  },
  // Peugeot
  {
    name: "Peugeot",
    image: makeImgPath + "peugeot.svg",
    cars: [
      {
        model: "208",
        type: CarType.HATCHBACK,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmission.MANUAL,
        fuelType: FuelType.DIESEL,
        fuelConsumption: " L/100 km",
        price: "",
        isActive: true,
        showInMain: false,
        image: carImgPath + "peugeot-208.webp",
      },
      {
        model: "2008",
        type: CarType.SUV,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmission.AUTOMATIC,
        fuelType: FuelType.DIESEL,
        fuelConsumption: " L/100 km",
        price: "",
        isActive: true,
        showInMain: false,
        image: carImgPath + "peugeot-2008.webp",
      },
      {
        model: "3008",
        type: CarType.SUV,
        year: 2023,
        doors: 5,
        seats: 5,
        transmission: Transmission.AUTOMATIC,
        fuelType: FuelType.DIESEL,
        fuelConsumption: " L/100 km",
        price: "",
        isActive: true,
        showInMain: false,
        image: carImgPath + "peugeot-3008.webp",
      },
    ],
  },
];
